"""add backups and schedules

Revision ID: f635f73f6995
Revises: 5881748df1a9
Create Date: 2026-09-15 12:31:32.863200

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'f635f73f6995'
down_revision: str | None = '5881748df1a9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('server_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('creating', 'ready', 'failed', name='backupstatus', native_enum=False, length=32), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('paths', sa.JSON(), nullable=True),
    sa.Column('exclude', sa.JSON(), nullable=False),
    sa.Column('schedule_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backups_schedule_id'), ['schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backups_server_id'), ['server_id'], unique=False)

    op.create_table('schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('server_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('cron', sa.String(length=100), nullable=False),
    sa.Column('action', sa.Enum('backup', 'restart', 'start', 'stop', 'command', name='scheduleaction', native_enum=False, length=32), nullable=False),
    sa.Column('command', sa.String(length=1000), nullable=True),
    sa.Column('keep', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=16), nullable=True),
    sa.Column('last_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_server_id'), ['server_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_server_id'))
        batch_op.drop_index(batch_op.f('ix_schedules_next_run_at'))

    op.drop_table('schedules')
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backups_server_id'))
        batch_op.drop_index(batch_op.f('ix_backups_schedule_id'))

    op.drop_table('backups')
    # ### end Alembic commands ###
