"""create servers

Revision ID: df6342b595c2
Revises: 
Create Date: 2026-09-15 00:16:06.505319

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'df6342b595c2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'installing', 'install_failed', 'stopped', 'starting', 'running', 'stopping', name='serverstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servers_template_id'), ['template_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servers_template_id'))

    op.drop_table('servers')
    # ### end Alembic commands ###
