"""add players and panel bans

Revision ID: 2310205f45df
Revises: b2d4f6a8c1e3
Create Date: 2026-09-16 23:18:14.694431

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '2310205f45df'
down_revision: str | None = 'b2d4f6a8c1e3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panel_bans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('server_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'kind', 'value')
    )
    with op.batch_alter_table('panel_bans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_panel_bans_server_id'), ['server_id'], unique=False)

    op.create_table('players',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('server_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('game_id', sa.String(length=128), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('slot', sa.String(length=16), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('online_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'key')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_server_id'), ['server_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_server_id'))

    op.drop_table('players')
    with op.batch_alter_table('panel_bans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_panel_bans_server_id'))

    op.drop_table('panel_bans')
    # ### end Alembic commands ###
